steps:
  # Install Node.js dependencies
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['install']

  # Run tests
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['test']
    env:
      - 'NODE_ENV=test'

  # Build Python AI backend as Cloud Function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'functions'
      - 'deploy'
      - 'medical-ai-backend'
      - '--source=.'
      - '--entry-point=app'
      - '--runtime=python39'
      - '--trigger=http'
      - '--allow-unauthenticated'
      - '--memory=512MB'
      - '--timeout=60s'
      - '--set-env-vars=OPENAI_API_KEY=${_OPENAI_API_KEY}'

  # Deploy Node.js backend to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--quiet'

  # Deploy frontend to Firebase Hosting
  - name: 'gcr.io/$PROJECT_ID/firebase'
    args:
      - 'deploy'
      - '--only=hosting'

substitutions:
  _OPENAI_API_KEY: 'your-openai-api-key'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s' 