default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "MediQuick.xcodeproj")
    build_app(scheme: "MediQuick")
    upload_to_testflight
  end
end 